### ISSUE TITLE
Server-Sent Events 的 retry 的解释不正确

### ISSUE THREAD

**Issue by duanyao** [ruanyf/jstutorial#100]
http://javascript.ruanyifeng.com/htmlapi/eventsource.html 提到：

> 浏览器默认的是，如果服务器端三秒内没有发送任何信息，则开始重连。

实际上并不是这样，我理解 [规范](https://html.spec.whatwg.org/multipage/comms.html#processing-model-9:reestablish-the-connection) 里面提到的重新连接的情形包括：（1）HTTP请求以200状态正常结束；（2）网络异常、服务器异常导致的连接失败或中断。而 retry 是指重连前的等待时间。

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
