### ISSUE TITLE
阮老师好，请问怎么通过js获取当前页面加载的所有资源的url和内容

### ISSUE THREAD

**Issue by Satann** [ruanyf/jstutorial#119]
我找到一个window.performance.getEntriesByType("resource");
这个只能抓到url列表，但是抓不到对应的contents，请问js有这样的接口么，支持这么做么

**Comment by hkongm** [comment]
`document.querySelectorAll('[src]')`

**Comment by zmzhydron** [comment]
只能抓到连接，下载要用nodejs

**Comment by ruanyf** [comment]
getEntriesByType() 方法好像做不到。

**Comment by Satann** [comment]
事实上我只需要抓ajax请求的内容，jquery提供了complete事件，刚好够用，多谢几位。
