### ISSUE TITLE
关于github pages

### ISSUE THREAD

**Issue by barretlee** [ruanyf/jstutorial#13]
Github help中看到要建立一个名为username.github.io才能正常显示博客，阮老师建立的是一个名为 jstutorial的项目也可以，这是怎么做到的？

**Comment by grahamle** [comment]
这是建的项目页，直接往 gh-pages 分支上推，然后通过不同的域名访问，如果有自己的域名，可以链接上去。具体可以看看我写的这个：http://grahamle.github.io/2013/09/ruby%E6%8A%98%E8%85%BE%E5%BB%BAgithub-pages/

**Comment by itfan** [comment]
https://github.com/itfan/7-days-nodejs  

@grahamle 

 请看一下我这个为什么无法直接访问呢？

http://itfan.github.io/7-days-nodejs

**Comment by ghost** [comment]
@itfan 放个 `.nojekyll` 文件进去试试？

**Comment by itfan** [comment]
@jakwings  成功！感谢！！！

**Comment by grahamle** [comment]
@itfan  不好意思，刚看到，也看到你推的node的文，赞。

**Comment by itfan** [comment]
@grahamle  共勉！

**Comment by weaming** [comment]
@itfan `CNAME`文件添加后，project pages 怎么设置 dns 呢

**Comment by ruanyf** [comment]
https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/
