### ISSUE TITLE
js 函数默认值

### ISSUE THREAD

**Issue by zhizunbao84** [ruanyf/jstutorial#139]
js函数默认值  现在是不是支持
function f(a = 1, b = 1){
  alert(b);
  alert(a);
}
这种写法了？

阮老师讲函数默认参数的时候 ，用的是这种方法：
function f(a) {
  (a !== undefined && a !== null) ? a = a : a = 1;
  return a;
}

**Comment by naicha-gg** [comment]
这是 ES6 的语法，可以去看阮一峰老师的另一本书：[《ECMAScript 6 入门》](http://es6.ruanyifeng.com/#docs/function#函数参数的默认值)

**Comment by zhizunbao84** [comment]
多谢指教
