### ISSUE TITLE
stdlib/array.md, 3.4 concat()中最后一个示例存在问题

### ISSUE THREAD

**Issue by troy351** [ruanyf/jstutorial#150]
原代码

``` javascript
[].concat.call({ a: 1 }, { b: 2 })
// [{ a: 1 }, { b: 2 }]

[].concat.call({ a: 1 }, [2])
// [{a:1}, 2]

// 等同于

[2].concat({a:1})
```

其中`[].concat.call({ a: 1 }, [2])`和`[2].concat({a:1})`并不等同。
虽然两者都可以将所需要的数组和对象拼接，从这个目的来说是相同的。但是结果数组上两者顺序是相反的，前者是`[{a:1}, 2]`，后者是`[2, {a:1}]`，就数组而言这两个数组并不相同，所以严格来说并不等同。
不过并不清楚应该如何纠正这个问题才能使其表述正确

**Comment by ruanyf** [comment]
谢谢指出，已经删除了”等同于“。
