### ISSUE TITLE
"此外，由于历史上JavaScript兼容HTML代码的注释，所以<!–和–>也被视为单行注释。"

### ISSUE THREAD

**Issue by Batur24** [ruanyf/jstutorial#153]
http://javascript.ruanyifeng.com/grammar/basic.html
1.5注释

> 此外，由于历史上JavaScript兼容HTML代码的注释，所以<!–和–>也被视为单行注释。

应该是：<!-和-->被视为单行注释

**Comment by Batur24** [comment]
包括后面的

> 需要注意的是，–>只有在行首

应该是-->

**Comment by ruanyf** [comment]
谢谢指出，源码里面是正确的，Markdown转码的时候错了，已经改正。
