### ISSUE TITLE
2.基本语法 => 2.4 对象 => 1.3 属性

### ISSUE THREAD

**Issue by yuler** [ruanyf/jstutorial#156]
http://javascript.ruanyifeng.com/grammar/object.html#toc3

``` javascript
var obj = {
  m1: function m1() {},
  m2: function () {}
};

obj.m1.name // m1
obj.m2.name // undefined
```

此处在 浏览器实现了 es6 的情况下 `obj.m2.name` 会返回 `m2`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

在文中强调说明下是不是好一些？

**Comment by ruanyf** [comment]
谢谢提醒，已经加入了文中。

**Comment by yuler** [comment]
😁
