### ISSUE TITLE
requestAnimationFrame部分的一处笔误.

### ISSUE THREAD

**Issue by xiujunma** [ruanyf/jstutorial#17]
requestAnimationFrame是浏览器用于定时循环操作的一个接口，类似于**_setTimeout**_，主要用途是按帧对网页进行重绘。
应该是 setInterval 更类似.

下面的代码中也应该是用的是 setInterval 而非 setTimeout.

**Comment by ruanyf** [comment]
我没错啊。

**Comment by xiujunma** [comment]
好吧.
看了这个才知道
http://www.paulirish.com/2011/requestanimationframe-for-smart-animating/
这太让人迷惑了.
