### ISSUE TITLE
“运行机制”部分的伪代码有歧义

### ISSUE THREAD

**Issue by pea3nut** [ruanyf/jstutorial#170]
```
function init(){
  { 耗时5ms的某个操作 }
  触发mouseClickEvent事件
  { 耗时5ms的某个操作 }
  setInterval(timerTask,10);
  { 耗时5ms的某个操作 }
}

function handleMouseClick(){
  耗时8ms的某个操作
}

function timerTask(){
  耗时2ms的某个操作
}
```

其中的_触发mouseClickEvent事件_应该是指用户触发吧？如果是js手动的去触发那么执行顺序则不会相同。

``` javascript
var elt =document.createElement('div');
elt.addEventListener('click' ,()=>console.log('click'));

console.log('run');
elt.click();
console.log('after click');
```

以上代码输出

```
run
click
after click
```

**Comment by pea3nut** [comment]
多问一下，js执行过程浏览器应该是假死状态吧，执行中间过程中用户可以触发事件吗？

**Comment by pea3nut** [comment]
原文链接：http://javascript.ruanyifeng.com/advanced/timer.html#section

**Comment by ruanyf** [comment]
谢谢指出，这段代码确实有问题，我已经删了。

**Comment by pea3nut** [comment]
阮一峰前辈加油~(≧▽≦)/~
看完了前辈你写的JS标准教程和ES6入门，收获很大，ES6实体书已购入支持 √
期待node.js部分！

**Comment by ruanyf** [comment]
近期目标是把《核心语法和浏览器模型》写完，Node 要等到明年写。

**Comment by naicha-gg** [comment]
@pea3nut 为何 js 手动触发执行顺序会不同？

**Comment by pea3nut** [comment]
@zhiquan-yu 
直接触发相当于调用函数了，而用户触发则相当于用setTimeout调用函数

> 参见：http://javascript.ruanyifeng.com/advanced/timer.html

**Comment by naicha-gg** [comment]
@pea3nut 用户触发事件的过程我明白的。“直接触发相当于调用函数了“，我没有看过这样的说法，但是你的例子说明是这样的，我不太能明白，能给个文档吗？
