### ISSUE TITLE
date那一章为什么会有一个<F12>乱入？

### ISSUE THREAD

**Issue by venicehsu** [ruanyf/jstutorial#171]
https://github.com/ruanyf/jstutorial/blob/gh-pages/stdlib/date.md
直接在上面这个网页内搜索<F12>即可搜到，不知道是什么意思。
new Date('2014-12-11')<F12>
// Thu Dec 11 2014 08:00:00 GMT+0800 (CST)

**Comment by ruanyf** [comment]
不好意思，输入错误，已经删除了。
