### ISSUE TITLE
内容错误

### ISSUE THREAD

**Issue by lanezhao** [ruanyf/jstutorial#179]
jstutorial/stdlib/array.md

var arr = new Array(2);
arr.length // 2
~~arr // [, ,]~~
arr // [ ,  ]

**Comment by zxhycxq** [comment]
**console.log()**的结果是
`[]`
我在**opera、chrome、360**里面测试是 `[]`.
**火狐**则是`[undefined, undefined]`
根据《JavaScript权威指南》数组一章节，

> 数组直接量的语法允许有可选的结尾的逗号，故[, ,]只有两个元素而非三个。

**Comment by lanezhao** [comment]
个人认为该文章讲的是 JavaScript 本身. 而并不是 JS 在不同浏览器的表现. 您所提的console.log()结果在浏览器中的表现我个人认为并不具有代表性. 我分别试了几种浏览器. 发觉因为 Developer Tools 的 Console 将输出经过了特别的"优化"以帮助开发者更容易的理解和使用使, 得其结果在我看来有时有点可笑. 如: 我的 Mac 版 Chrome 54.0.2840.87 给出的结果是 "[undefined × 2]" ; 我的 Mac 版 FireFox 46.0.1 给出的结果是 "Array [ <2 个空的存储位置> ]" ....  至于您提到的《JavaScript权威指南》的解释, 我刚好手边有一本第五版, 翻了翻没找到你说的那段. 但在我所掌握的有限知识中 JS 的语法没有 "可选的结尾的逗号" 一说. 特别在 JSON 中结尾使用逗号是要报错的. 所以在这里我个人更倾向于 Node.js 给出的 console.log() : [ ,  ] . 我认为这是没有经过加工的更纯粹的结果. 也是更符合常理的结果, 也是更不容易使学习者产生困惑的结果.

**Comment by ruanyf** [comment]
原来的写法其实没错，不过为了防止误解，我改成`[ undefined x 2 ]`。

**Comment by zxhycxq** [comment]
@lanezhao  最近看《你不知道的javascript》，里面提到相关的内容：
[https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch3.md](url)
“What!? Firefox puts an extra ”开头那部分

**Comment by lanezhao** [comment]
@zxhycxq 刚刚才看到您的回复. 没有看 Git Notification 的习惯(反正也没人联系我). 您给我的链接已经失效了. 但根据链接里边得的 keywords 找到了这篇 https://github.com/getify/You-Dont-Know-JS/blob/31e1d4ff600d88cc2ce243903ab8a3a9d15cce15/types%20%26%20grammar/ch3.md . 

我没太看懂您分享给我这篇文章的含义. 我理解可能你想解释是 ES5 造成了这一问题, 而这种写法是对的. 我之前确实不知道这一点(我的JS知识很有限). 但在我看来 ES5 的这种选择本身就是个错误啊! "," 的含义就代表未结束, 有后续内容的意思啊. 在数组中作为分隔符出现就代表着后续有将要被分割的内容啊. 这样设计明摆着就会非常容易造成歧义和困惑.
