### ISSUE TITLE
index.md页面链接失效

### ISSUE THREAD

**Issue by zxhycxq** [ruanyf/jstutorial#180]
可能是之前的版本链接吧。
估计大多数人都是直接在博客上面看的，很少从Github上面看。

**Comment by ruanyf** [comment]
你说的`index.md`在哪里？

**Comment by zxhycxq** [comment]
抱歉，我表述不准确，就是这个jstutorial 根目录下的index.md。打开里面的链接，显示404.

**Comment by ruanyf** [comment]
这个文件是为了自动生成 index.html，所以链接并没有错误。Github上面确实无效的。
