### ISSUE TITLE
函数章节运行结果写错了

### ISSUE THREAD

**Issue by MAYDAY1993** [ruanyf/jstutorial#186]
你好 在1.2章函数－函数的重复声明中 第一个运行结果应该是1 写成2了 
![2016-11-30 11 38 47](https://cloud.githubusercontent.com/assets/14831051/20739681/dacdd018-b6f7-11e6-936d-13945f19d5a2.png)
链接http://javascript.ruanyifeng.com/grammar/function.html

**Comment by ruanyf** [comment]
原文没错。
