### ISSUE TITLE
函数本身的作用域返回结果

### ISSUE THREAD

**Issue by MAYDAY1993** [ruanyf/jstutorial#187]
你好 http://javascript.ruanyifeng.com/grammar/function.html 这一页3.3一节中return bar;应该是return bar();吧 否则没有调用bar函数 只会返回bar函数
![2016-11-30 2 53 08](https://cloud.githubusercontent.com/assets/14831051/20742715/c2d292ae-b70c-11e6-8b00-405052825278.png)

**Comment by MAYDAY1993** [comment]
另外 最后一句 调用f 不应该写成f() 吧 f是一个变量 不是一个函数  被foo函数赋值  所以直接调用f就好啦 这样写：
![image](https://cloud.githubusercontent.com/assets/14831051/20742964/91666b8a-b70e-11e6-9248-58d1435ea5ee.png)

**Comment by ruanyf** [comment]
请运行代码后再发言。
