### ISSUE TITLE
isPrototypeOf 书写错误

### ISSUE THREAD

**Issue by MAYDAY1993** [ruanyf/jstutorial#188]
阮老师好，在 [http://javascript.ruanyifeng.com/oop/prototype.html#toc10](url) 中， isPrototypeOf 书写错误
![image](https://cloud.githubusercontent.com/assets/14831051/20881766/d7d4108c-bb18-11e6-9a9a-c63c9e5393a3.png)

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
