### ISSUE TITLE
ChildNode接口，before()，after()，replaceWith()这三个方法目前已有浏览器支持

### ISSUE THREAD

**Issue by JiayingZeng** [ruanyf/jstutorial#192]
在DOM模型概述章节，6.2ChildNode 接口，before()，after()，replaceWith()已在Chrome,FireFox,Opera最新版测试可行。

![image](https://cloud.githubusercontent.com/assets/8372202/21216942/86dd8108-c2e4-11e6-92bf-b2ca1fe1e6ef.png)

![image](https://cloud.githubusercontent.com/assets/8372202/21216904/51e5db62-c2e4-11e6-8521-bb33b404ca3b.png)

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
