### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by MAYDAY1993** [ruanyf/jstutorial#197]
你好 这里[http://javascript.ruanyifeng.com/bom/engine.html](url)，
![image](https://cloud.githubusercontent.com/assets/14831051/21536021/1cbce302-cdb8-11e6-9bb4-dd88d8c51e64.png)

**Comment by ruanyf** [comment]
谢谢指出，已经改正。

**Comment by ghost** [comment]
http://javascript.ruanyifeng.com/nodejs/fs.html#toc0
![image](https://cloud.githubusercontent.com/assets/9296136/25689578/0f7f3b6a-30bc-11e7-951b-f2bc2ff9fef2.png)
 老大，这里是process.cwd()吧

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
