### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by MAYDAY1993** [ruanyf/jstutorial#199]
hello [,这一页](http://javascript.ruanyifeng.com/dom/event.html#toc12) 里 ->这三种
![error](https://cloud.githubusercontent.com/assets/14831051/21673839/df6c8c38-d365-11e6-9243-29650947af0d.png)

**Comment by ruanyf** [comment]
没错啊，不是三种，是三阶段。

**Comment by MAYDAY1993** [comment]
傻了傻了 看成了三种阶段 。。。。
