### ISSUE TITLE
建议及时关闭已经解决的 Issue

### ISSUE THREAD

**Issue by ghost** [ruanyf/jstutorial#20]
免得大家浪费时间点进去查看 issue 。

**Comment by ruanyf** [comment]
我是把issues当作论坛用。都关掉了，感觉好像没人发言了。

另外，也可以在issues讨论怎么学习JavaScript，或者一些开发问题。

**Comment by ghost** [comment]
原来如此，只是这样太容易让人误会了，issue 堆积多了会让人以为这个项目问题很多，或者你对 issue 的处理不够勤快呢。

**Comment by ruanyf** [comment]
啊，真是有这个问题，我没想到。

这样吧，现在这里人很少，我先暂时保留一些发言。如果将来人多了，就及时关闭过时的issue。

**Comment by achun** [comment]
可以挂第三方社会化评论用于交流, 比如 disqus 啥的

**Comment by ZoeyYoung** [comment]
比较在意PR都没有合或关闭...不知道PR里面的问题有没有解决，看评论才知道

**Comment by ruanyf** [comment]
现在留下来的PR都是一年前的，争取最近都处理掉。
