### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by sheldonshen** [ruanyf/jstutorial#203]
阮老师好,http://javascript.ruanyifeng.com/dom/document.html#toc30
![capture](https://cloud.githubusercontent.com/assets/9124518/22133556/e8567c9a-defb-11e6-80d6-782140af0add.PNG)
当参数是null,在IE11,FF,Chrome下测试是不会报错的.

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
