### ISSUE TITLE
有一个地方需要更严谨一些

### ISSUE THREAD

**Issue by liuzhenbase** [ruanyf/jstutorial#206]
[在函数一章](http://javascript.ruanyifeng.com/grammar/function.html#toc15)的小节4.2参数的省略：

> 但是，没有办法只省略靠前的参数，而保留靠后的参数。如果一定要省略靠前的参数，只有显式传入undefined。

而在数据类型的`null`与`undefined`的区别[一节](http://javascript.ruanyifeng.com/grammar/types.html#toc4)中这么说：

> null表示空值，即该处的值现在为空。比如，调用函数时，不需要传入某个参数，这时就可以传入null。

自相矛盾，希望修正

**Comment by ruanyf** [comment]
谢谢指出，已经改正了`null`与`undefined`的区别这一部分。
