### ISSUE TITLE
大神能否给讲一下 目前浏览器 无痕模式 都限制了哪些功能了么？

### ISSUE THREAD

**Issue by Jerry-goodboy** [ruanyf/jstutorial#208]
浏览器的无痕模式，想必大家都用过，我们最近在开发一款webAPP，用到了H5的很多新特性，如 localstorage等等，可是无痕模式下这个功能是被禁掉的，导致我们的系统根本无法访问，所以想请大神指导一下无痕模式下浏览器究竟都限制了哪些功能，对无痕模式下的开发能否给前端一些建议？

**Comment by Jerry-goodboy** [comment]
@ruanyf @jakwings @jprosper @haishanh @poying 先谢谢各位了！！！

**Comment by ruanyf** [comment]
请阅读维基百科。https://en.wikipedia.org/wiki/Privacy_mode
