### ISSUE TITLE
ifelse语句

### ISSUE THREAD

**Issue by mark5566** [ruanyf/jstutorial#209]
http://javascript.ruanyifeng.com/grammar/basic.html#toc14
在讲述if else部分有个疑问，下面语句
if (m !== 1)
if (n === 2) console.log('hello');
else console.log('world');
相当于：
if (m !== 1) {
  if (n === 2) {
    console.log('hello');	
  } else {
    console.log('world');
  }
}
这里应该有问题，个人觉得如下
if (m !== 1) {
}
  if (n === 2) {
    console.log('hello');	
  } else {
    console.log('world');
  }

**Comment by ruanyf** [comment]
试试下面代码就清楚了。

```javascript
if (m !== 1)
if (n === 2) console.log('hello');
else console.log('world');
else console.log('end');
```

**Comment by mark5566** [comment]
var m=1
		var n=2
		if (m !== 1) 
		console.log("m!==1")
		if (n === 2) console.log('hello');
		else console.log('world');
这样子打印，只打印出了hello。。怎么回事儿？
