### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by wangding** [ruanyf/jstutorial#210]
阮一峰老师：
　　我这两天在学习 Jekyll 做静态网站，有两个地方比较困惑，请您不吝赐教啊！
1. Jekyll 网站的官方资料说，发的帖子是：年-月-日-标题.md 格式的文件，我发现你的 jstutorial 仓库，不是这个文件格式的，如何做到的啊？
2. Jekyll 网站的帖子都放到 _posts 文件夹下的，你的文章可以放到自己命名的文件夹下面，请问是如何做到的啊？

谢谢啊！

**Comment by ruanyf** [comment]
我好久不看 Jekyll 了，有点忘记了。好像只有 Blog 才需要命名成那样，平常的文件只要有 Yaml 头，都会转码的。
