### ISSUE TITLE
勘误(?)

### ISSUE THREAD

**Issue by simymo** [ruanyf/jstutorial#211]
http://javascript.ruanyifeng.com/grammar/conversion.html

1.1 （2）对象的转换规则

简单的规则是，Number方法的参数是对象时，将返回NaN。

一个反例： Number([1]) === 1 //true

**Comment by ruanyf** [comment]
谢谢指出，我改了一下。应该是除了单个数值的数组，其他对象转换后，都返回`NaN`。
