### ISSUE TITLE
CommonJS中的模块加载机制部分

### ISSUE THREAD

**Issue by Silence-jk** [ruanyf/jstutorial#217]
// main.js
var counter = require('./lib').counter;
var incCounter = require('./lib').incCounter;

console.log(counter);  // 3
incCounter();
console.log(counter); // 3
counter即使没输出，lib.js模块内部的变化也影响不到counter

**Comment by ruanyf** [comment]
那是以前的稿子，可能说的不清楚，以下面的内容为准。

http://es6.ruanyifeng.com/#docs/module-loader#ES6-模块与-CommonJS-模块的差异
