### ISSUE TITLE
nodejs中config字段的补充

### ISSUE THREAD

**Issue by naruco** [ruanyf/jstutorial#224]
在[package.json]( jstutorial/nodejs/packagejson.md )的config字段一节中，**progress.env.npm_package_config_port**应该在执行npm run <stage>的提前下才能获取。
> When running scripts (see npm-scripts) the package.json "config" keys are overwritten in the environment if there is a config param of .....

我建议作补充说明一下，对初学者比较直观。比如添加
>npm run start
>执行如上命令即可

我个人按照原文内容修改好config字段后，运行**node index.js**，progress.env.npm_package_config_port始终返回的只是undefined，所以很困惑。直到看了npm的document才明白。

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
