### ISSUE TITLE
npm-shrinkwrap一节中的文字错误

### ISSUE THREAD

**Issue by naruco** [ruanyf/jstutorial#225]
[npm-shrinkwrap](https://github.com/ruanyf/jstutorial/blob/gh-pages/nodejs/npm.md#npm-shrinkwrap)一节中，“**以来**模块”应为“**依赖**模块”
>npm shrinkwrap的作用是锁定当前项目的以来模块的版本。

我是不是太细心了，呵呵~

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
