### ISSUE TITLE
定时器原理章节一些疑问，如果setTimeout(fn,5000)中fn是立即执行函数

### ISSUE THREAD

**Issue by islishude** [ruanyf/jstutorial#226]
>setTimeout和setInterval的运行机制是，将指定的代码移出本次执行，等到下一轮 Event Loop 时，再检查是否到了指定时间。如果到了，就执行对应的代码；如果不到，就等到再下一轮 Event Loop 时重新判断。

```
var i = 5
setTimeout((function (i) {
    console.log(i);
})(i), 5000);
```
如代码所示，fn为立即执行函数，但是如果原理是将指定的代码移除，那么应该是 5s 后输出 i 的值，但是事实上，立刻就会输出 i 的值，那么？

所以说立即执行函数作为参数在定时器中是特例？

我思考了一下，setTimeout 可以接受函数或者字符串作为参数，立即执行函数应该等价于 undefined，所以上述的代码应该等价于

```
setTimeout(undefined,5000)
```

由于是立即执行函数，所以会立即输出结果，不知道我这样理解对不对..

**Comment by isLishude** [comment]
同理如果把代码改为这样子，

```
 var j = 6;

function fn(){
    console.log(j)
}

setTimeout(fn(), 5000);
```
那也就是说fn其实是个延迟执行的函数，如果需要执行状态就不会等待。。？

**Comment by ruanyf** [comment]
```javascript
var i = 5;
var x = (function (i) {
    console.log(i);
})(i);
setTimeout(x, 5000);
```
