### ISSUE TITLE
一个小的文字描述错误

### ISSUE THREAD

**Issue by caiyongmin** [ruanyf/jstutorial#231]
__链接__：[Here](http://javascript.ruanyifeng.com/grammar/number.html#toc5).

__期望__：应该是 8 个，即（且只用到 0-7 的**八**个阿拉伯数字的数值）。

__截图__：
![image](https://user-images.githubusercontent.com/11053605/27135709-d9081dbc-514b-11e7-832d-eff466762519.png)

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
