### ISSUE TITLE
RegExp 对象一节，代码描述错误

### ISSUE THREAD

**Issue by caiyongmin** [ruanyf/jstutorial#232]
__链接__：[Link](http://javascript.ruanyifeng.com/stdlib/regexp.html).

__期望__：`2,` 和 `5` 之间不应该有空格，如果有，则会返回 false。

__截图__：
![image](https://user-images.githubusercontent.com/11053605/27259654-68e784da-544a-11e7-9499-f3ee6c5b7d20.png)

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
