### ISSUE TITLE
数据类型转换一节，文字描述有误

### ISSUE THREAD

**Issue by caiyongmin** [ruanyf/jstutorial#233]
__链接__：[Link](http://javascript.ruanyifeng.com/grammar/conversion.html).

__期望__：1. 应该是（包含单个数值的数组）；2. 空数组也能被 `Number()` 函数转化成有效数字 `0`。

__截图__：
![image](https://user-images.githubusercontent.com/11053605/27259686-73c12612-544b-11e7-872b-7b88e20aabf4.png)

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
