### ISSUE TITLE
关于数值表示上限的解释问题

### ISSUE THREAD

**Issue by alvarto** [ruanyf/jstutorial#24]
引用：http://javascript.ruanyifeng.com/grammar/number.html#toc3

> 另一方面，64位浮点数的指数部分的长度是11个二进制位，意味着指数部分的最大值是2047（2的11次方减1）。所以，JavaScript能够表示的数值范围为(-2<sup>2048</sup>, 2<sup>2048</sup>)，超出这个范围的数无法表示。

这是不正确的说法。
第一，指数是以偏移法表示的，
第二，指数的0值与2047值被用于表示特殊值
第三，表示上限不能忽略前方的有效数字位

真正有意义的表示上下限，是这两个区间[-(2<sup>53</sup>-1)·(2<sup>971</sup>),-2<sup>-1074</sup>]，[2<sup>-1074</sup>，(2<sup>53</sup>-1)·(2<sup>971</sup>)]，加上一个点0。

详细解释见我的这篇博文：https://segmentfault.com/a/1190000000407658

**Comment by ruanyf** [comment]
谢谢指出，我确实写错了。

已经改过来了，请看看现在这样是否可以：

> "另一方面，64位浮点数的指数部分的长度是11个二进制位，意味着指数部分的最大值是2047（2的11次方减1）。也就是说，64位浮点数的指数部分的值最大为2047，分出一半表示负数，则JavaScript能够表示的数值范围为21024到2-1023，超出这个范围的数无法表示。"

-- [《数值》](http://javascript.ruanyifeng.com/grammar/number.html)

另外，我把你的文章加入了“参考链接”。

**Comment by alvarto** [comment]
特殊值0和2047被保留的缘故，(-1023,1024)是开区间，指数的表示范围2^-1022-2^1023。
谢引用:)

**Comment by ruanyf** [comment]
谢谢提醒，现在将原文改为下面这样：

> 如果指数部分等于或超过最大正值1024，JavaScript会返回Infinity，这称为“正向溢出”；如果等于或超过最小负值-1023（即非常接近0），JavaScript会直接把这个数转为0，这称为“负向溢出”。事实上，JavaScript将指数部分的两个极端值（11111111111和00000000000），就分别定义为Infinity和0。

**Comment by alvarto** [comment]
11111111111还有NaN的情形，00000000000还有非规格化值的情形。很难一下子概括全

**Comment by ruanyf** [comment]
我把原文又改了一下。

“事实上，JavaScript对指数部分的两个极端值（11111111111和00000000000）做了定义，11111111111的一个含义就是Infinity，00000000000的一个含义就是0。”
