### ISSUE TITLE
Safari 10.1+ 已经支持 IndexedDB

### ISSUE THREAD

**Issue by islishude** [ruanyf/jstutorial#240]
![image](https://user-images.githubusercontent.com/24730006/27897683-4612f33c-6254-11e7-94da-193d7674d11f.png)

![image](https://user-images.githubusercontent.com/24730006/27897698-53cd9bb2-6254-11e7-8cbb-dc0390112323.png)

https://caniuse.com/#search=indexedDB

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
