### ISSUE TITLE
浏览页面二级目录排序错误

### ISSUE THREAD

**Issue by lwshang** [ruanyf/jstutorial#243]
进入某一具体章节后，想要阅读下一章节会自然的想要在通过顶部菜单点选。但是二级菜单没有按照正确顺序排序。为了能够确保按顺序阅读，只能每次都返回主页面。希望能够添加上一章和下一章这样的快捷按钮。
<img width="1092" alt="screen shot 2017-07-08 at 12 26 37" src="https://user-images.githubusercontent.com/13881324/27987304-82a47ce0-63d9-11e7-85a7-3ba654e31569.png">

**Comment by ruanyf** [comment]
一直在改章节，所以没做二级目录排序。

后面半年会将这本书定稿，到时候会做网站新版。
