### ISSUE TITLE
顶部下拉菜单目录顺序错误

### ISSUE THREAD

**Issue by ivysrono** [ruanyf/jstutorial#244]
该错误似乎在各个模块都不同程度存在。
错乱的下拉菜单：
![default](https://user-images.githubusercontent.com/2649544/27991642-a75d3414-64b0-11e7-9773-29bdf2775dc4.png)
正确顺序：
![default](https://user-images.githubusercontent.com/2649544/27991651-c1328a10-64b0-11e7-8c86-58cd256db820.png)

**Comment by ruanyf** [comment]
章节的顺序一直在调整，所以这里就没做固定排序。

今年下半年，我会将这本书完稿。到时就可以给出正确顺序了。
