### ISSUE TITLE
关于模块加载机制

### ISSUE THREAD

**Issue by rylan0119** [ruanyf/jstutorial#246]
http://javascript.ruanyifeng.com/nodejs/module.html#toc13

您这里指出
> CommonJS模块的加载机制是，输入的是被输出的值的拷贝。也就是说，一旦输出一个值，模块内部的变化就影响不到这个值。

然后您举了个例子，例子中counter是基本数据类型，但我把counter改成对象类型，发现结果有些不同，代码如下：

```js
// lib.js
var counter = {
    count: 3
};
function incCounter() {
    counter.count++;
}
module.exports = {
    counter: counter,
    incCounter: incCounter
};

// main.js
var counter = require('./lib.js').counter;
var incCounter = require('./lib.js').incCounter;

console.log(counter.count); 
incCounter();
console.log(counter.count); 
```
而且您例子中`var counter = require('./lib').counter;`获得的是基本数据类型，counter这个变量已经就与'lib'这个模块没有关系了，下边调用完模块中获得的函数后又判断了一遍counter的值感觉是没意义的，感觉例子不是很恰当。不知道您关于CommonJS模块加载的描述是否准确，作为一个初学者很迷惑，希望看到可以解答下。

**Comment by ruanyf** [comment]
如果输出对象，绑定是引用，而不是里面的值。你可以试试下面的代码。

```javascript
// lib.js
var counter = {
  count: 3
};

function incCounter() {
    counter = {count: 4};
}
module.exports = {
    counter: counter,
    incCounter: incCounter
};
```

**Comment by rylan0119** [comment]
我用下面的方法试了下

```js
var counter = require('./lib.js').counter;
var incCounter = require('./lib.js').incCounter;

console.log(counter.count);   // 3
incCounter();
console.log(counter.count);  // 3
```
您的这个例子counter是一个对象的引用，然后将这个引用通过module.exports输出，incCounter这个函数改变了counter的值，现在模块中变量counter的值为{count: 4},而module.exports输出的对象中属性counter仍旧指向{count: 3}，结果两次输出结果都是3,但感觉这样测试容易让人误解。

您表达的意思是`一旦输出一个值，模块内部的变化就影响不到这个值。`，输出的这个值是通过module.exports输出的，模块内部变化指的是什么(这让我很费解)？您举的例子改变了模块内的变量counter,但这个变量是一个引用，只是当了一次“中间人”，将他的值付给了module.exports的属性，您所表述的“值”应该是指{count：3}这个对象吧，但例子中没有在内部改变这个值，只是改变了之前这个值的一个引用counter。

你表达的模块内部的变化是指影响module.exports的变化，还是指其他什么?

**Comment by ruanyf** [comment]
CommonJS 模块的输出会被 Node 缓存，模块内部的变化不会影响输出值。

如果模块输出的是对象，缓存的是这个对象的地址，所以属性变化依然可以反应出来。

教材里面的讲解，可能不是很清楚，但是并没有错。

**Comment by rylan0119** [comment]
OK，总之看了您关于CommonJS的介绍知道了基本的用法，感谢您抽出时间回复。
