### ISSUE TITLE
document.documentURI，document.URL会随锚点变化

### ISSUE THREAD

**Issue by Silence-jk** [ruanyf/jstutorial#252]
DOM模型>document节点 4.1

document.URL
"https://dom.spec.whatwg.org/#events"
document.URL
"https://dom.spec.whatwg.org/#biblio-xml-names"

document.documentURI
"https://dom.spec.whatwg.org/#biblio-xml-names"
document.documentURI
"https://dom.spec.whatwg.org/#events"

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
