### ISSUE TITLE
RegExp正则对象-属性和方法：lastIndex属性案例解析错误

### ISSUE THREAD

**Issue by yuanhaohao** [ruanyf/jstutorial#255]
![image](https://user-images.githubusercontent.com/21191067/28760169-3191b772-75d7-11e7-9c85-6d9782a5f0fe.png)
lastIndex返回下一次开始搜索的位置，所以这里不是“五”，应该是“四”，“代码指定从字符串的第四个位置开始搜索”

**Comment by ruanyf** [comment]
这个的意思是 index 是4，但其实是第五个位置。我表达得不好。

**Comment by yuanhaohao** [comment]
噢噢晓得辣，谢谢阮大大😊


在 2017年7月31日，上午10:36，Ruan YiFeng <notifications@github.com<mailto:notifications@github.com>> 写道：


这个的意思是 index 是4，但其实是第五个位置。我表达得不好。
