### ISSUE TITLE
建议：运算符中可以提及一下NaN与正常数字之间的比较

### ISSUE THREAD

**Issue by yzajoee** [ruanyf/jstutorial#261]
我今天写代码时有个bug是数值弄错，导致undefined和数字比较，undefined会转换为数值NaN，然后我是抱着查工具书的心态看了下阮大的书去查一下NaN和数字的比较结果是什么，不过文中没有提及到。
NaN作为运算数的时候，比较运算符总是生成false，这个现象比较有趣，建议加入到文中

**Comment by ruanyf** [comment]
谢谢提醒，已经添加了这部分。
