### ISSUE TITLE
nodejs/events.md中this的使用问题

### ISSUE THREAD

**Issue by gyj1278** [ruanyf/jstutorial#262]
您好，阮老师：
simon.on('bark', function () {
  console.log(this.name + ' barked');
});
这段代码，我测试过，this.name是取不到值的，为undefined！
我对this理解的也不够深，不太懂是为啥。
node版本：4.4.3

**Comment by ruanyf** [comment]
看下面网址。
http://javascript.ruanyifeng.com/oop/this.html
