### ISSUE TITLE
object中关于对判断数据类型封装的type.isNaN( )和type.isInfinite( )

### ISSUE THREAD

**Issue by FreedGo** [ruanyf/jstutorial#264]
![image](https://user-images.githubusercontent.com/17702426/29859997-183bcbdc-8d97-11e7-8a5a-e8c46e5b8b3d.png)
您这一章在讲object的时候，给封装了一个type案例，以用来判断数据类型，其中的type.isNaN( NaN )为false，您这个地方讲的是用Object.prototype.toString.call()方法来判断，NaN本身类型为number，得出这个结果也是对的，但是我们实际使用中如果要判断数据是否NaN的话，是想能得到一个确定的结果，使用的是您在number那一章中的NaN !== NaN方法，也就是这个地方封装的type.isNaN( )并没有使用价值，另外type.Infinite( ),也是如此，建议这个地方可以去掉这两个。

**Comment by ruanyf** [comment]
谢谢指出，已经更正了。
