### ISSUE TITLE
Array.prototype.forEach() 不能中断遍历的解释有误

### ISSUE THREAD

**Issue by islishude** [ruanyf/jstutorial#268]
http://javascript.ruanyifeng.com/stdlib/array.html#toc15

![image](https://user-images.githubusercontent.com/24730006/30476276-19c93816-9a3c-11e7-8ff5-7f0cbf4039df.png)

而我测试下面代码是可以实现中断的

```js
var arr = [1, 2, 3]

arr.forEach(function(value, key){
    if(key === 2) return
    console.log(value)
})

// 输出
// 1
// 2
```
[MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)上关于这个解释比较好。

>注意： 没有办法中止或者跳出 forEach 循环，除了抛出一个异常。如果你需要这样，使用forEach()方法是错误的，你可以用一个简单的循环作为替代。如果您正在测试一个数组里的元素是否符合某条件，且需要返回一个布尔值，那么可使用 Array.every 或 Array.some。如果可用，新方法 find() 或者findIndex() 也可被用于真值测试的提早终止。

**Comment by mlyknown** [comment]
arr.forEach(function(value, key){
   console.log(value); if(key === 2) return 
})
这样子再试哈？

**Comment by islishude** [comment]
> arr.forEach(function(value, key){
> console.log(value); if(key === 2) return
> })
> 这样子再试哈？

你这样写当然能输出1 2 3

**Comment by ruanyf** [comment]
这里“打断”的意思是不再执行后面的循环了，你的写法依然会继续循环。

```javascript
var arr = [1, 2, 3, 4]

arr.forEach(function(value, key){
    if(key === 2) return
    console.log(value)
})
// 1
// 2
// 4
```

**Comment by islishude** [comment]
嗯嗯，这里确实没注意到，MDN上的解释还有一条除非抛出一条异常，这里就能中断了。

```js
var arr = [1, 2, 3, 4]
arr.forEach(function(value, key){
    if(key === 2) throw new Error('error')
    console.log(value)
})
```

我建议在后面加上『除非抛出一条异常』

**Comment by ruanyf** [comment]
抛出异常是整个进程终止。

2017年9月16日 12:40，"isLishude" <notifications@github.com>写道：
