### ISSUE TITLE
读者纠错

### ISSUE THREAD

**Issue by baoxd** [ruanyf/jstutorial#287]
阮兄好！
       面向对象编程----prototype章节：

`function A() {}
var a = new A();
a instanceof A // true

function B() {}
A.prototype = B.prototype;
a instanceof A // false`

> 上面代码中，a是A的实例。修改了A.prototype以后，constructor属性的指向就变了，导致instanceof运算符失真。

上面之所以instanceof失败，我觉得不是因为原型对象constructor改变导致的，实际改变后会返回真，真正失败的原因是a对象原型链上的__proto__对象不再和A.prototype相等（===）导致的。

**Comment by ruanyf** [comment]
谢谢指出，原文确实错了，已经改正。
