### ISSUE TITLE
读者纠错

### ISSUE THREAD

**Issue by baoxd** [ruanyf/jstutorial#288]
阮兄好！
      语法专题--promise章节（用法辨析）：
`doSomething().then(function () {
  return doSomethingElse();
}).then(finalHandler);`

> 为了便于讲解，下面这四种写法都再用then方法接一个回调函数finalHandler。写法一的finalHandler回调函数的参数，是doSomethingElse函数的运行结果。

如果doSomethingElse()的运行结果是异步对象，finalHandler不是该函数的执行结果，而是异步对象产生的数据。下面是jquery对Promise的实现：

`var returned = fn && fn.apply(this, arguments);
if (returned && jQuery.isFunction(returned.promise)) {
      // 上次的函数队列执行完毕，告知下次promise状态修改，并传递参数
returned.promise()
.done(newDefer.resolve)
.fail(newDefer.reject)
.progress(newDefer.notify);
} else {
     newDefer[tuple[0] + "With"](this === promise ? newDefer.promise() : this, fn ? [returned] : arguments);
}`

**Comment by ruanyf** [comment]
你说得对，确实如此。

这里为了简化讨论，假定`doSomethingElse`是一个同步函数，我没写清楚。
