### ISSUE TITLE
prototype 对象章节

### ISSUE THREAD

**Issue by ghost** [ruanyf/jstutorial#289]
http://javascript.ruanyifeng.com/oop/prototype.html
Object.create()这个函数的讲解时候：
JavaScript 提供了Object.create方法，用来满足这种需求。该方法接受一个对象作为参数，然后以它为原型，返回一个实例对象。该实例完全【继承继承】原型对象的属性。
貌似重复了

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
