### ISSUE TITLE
this章节中有个问题一直搞不懂想问一下

### ISSUE THREAD

**Issue by transient-ad** [ruanyf/jstutorial#290]
2.3中
var obj ={
  foo: function () {
    console.log(this);
  }
};

obj.foo() // obj         为什么 我的是显示  foo而不是obj？

**Comment by shushu2013** [comment]
@hujifeiisgood 
你是把 {foo: f} 看成是 foo 吧 ！
![image](https://user-images.githubusercontent.com/6076072/33658796-e589dbb0-dab8-11e7-9471-59eadd7cb9b5.png)
打印的 {foo:f}  就是 obj 这个对象的字面量表示法

**Comment by ruanyf** [comment]
确实浏览器不会输出`obj`，只会输出`{foo: f}`，其实就是`obj`。
