### ISSUE TITLE
阮老师，请问这个项目如何在本地运行啊

### ISSUE THREAD

**Issue by meishadevs** [ruanyf/jstutorial#292]
我有时候要在没有网络的时候看这本书，请问将整个项目克隆到本地后，如何在本地运行

**Comment by ruanyf** [comment]
你要装 Jekyll。不过，这个项目马上要彻底重构了，新的内容会放在另一个仓库。

**Comment by snow212-cn** [comment]
那现在到底是重构了没有，新的内容又是在什么地方

**Comment by ruanyf** [comment]
https://wangdoc.com/javascript/index.html
