### ISSUE TITLE
Koa框架 Response对象小节 示例代码错误

### ISSUE THREAD

**Issue by JimLiuxinghai** [ruanyf/jstutorial#294]
http://javascript.ruanyifeng.com/nodejs/koa.html#toc9

描述Response.type时，示例代码错误

![error](http://7xp1lq.com1.z0.glb.clouddn.com/error.png)

**Comment by ruanyf** [comment]
这个页面不维护了，新版看这里 http://www.ruanyifeng.com/blog/2017/08/koa.html
