### ISSUE TITLE
[错误] 2.7 函数 中的1.2函数的重复声明 

### ISSUE THREAD

**Issue by shanhaoli** [ruanyf/jstutorial#295]
> function f() {
  console.log(1);
}
f() // 2

>function f() {
  console.log(2);
}
f() // 2

第一次定义函数f()，调用后应当打印1。
应带修改注释为1，如下：
> function f() {
  console.log(1);
}
f() // 1

>function f() {
  console.log(2);
}
f() // 2

**Comment by ruanyf** [comment]
原文没错。你必须把这段代码一次性运行，不能先执行第一段，再执行第二段。

**Comment by shanhaoli** [comment]
不好意思，我理解错了。
