### ISSUE TITLE
Array.prototype.splice.call() 并不能把对象转换为含有元素的数组

### ISSUE THREAD

**Issue by hr837** [ruanyf/jstutorial#297]
1. 针对含有length属性的对象
`let temp = {
	0:'A',
    1:'B',
    2:'C',
    length:3
}`
// temp: {0: "A", 1: "B", 2: "C", length: 3}
`let arr = Array.prototype.splice.call(temp)`
// arr: []
2.  转换字符串的时候异常
`var sc = Array.prototype.splice.call('abcdef')`
：Error
VM213:2 Uncaught TypeError: Cannot assign to read only property 'length' of object '[object String]'
    at String.splice (<anonymous>)
    at <anonymous>:2:33

**Comment by ruanyf** [comment]
不是`splice`方法，而是`slice`方法。

```javascript
Array.prototype.slice.call(temp)
// ["A", "B", "C"]
```

我可能不小心写错了，你是哪一章看到的？
