### ISSUE TITLE
"Javascript"有无必要改成"JavaScript"?

### ISSUE THREAD

**Issue by zzxadi** [ruanyf/jstutorial#3]
文章中有很多地方没有区分`JavaScript`中“S”的大小写，虽然不影响阅读和理解，但感觉不统一，想问作者，有无必要将"Javascript"改成"JavaScript"?

**Comment by ruanyf** [comment]
刚开始的时候，我写成Javascript，后来都统一改成JavaScript了。

定稿的时候，还没有改的那些会全部改掉的。
