### ISSUE TITLE
storage事件问题

### ISSUE THREAD

**Issue by yueswing07** [ruanyf/jstutorial#301]
storage事件 我在chrome浏览器下  实践发现 有效果。
而sessionStorage当前窗口变量 只在一个窗口有效 所以不存在 页面间传值可能。
同一个域名 多页面 sessionStorage各自不同。
所以 我觉得下面的内容 需要修正下
http://javascript.ruanyifeng.com/bom/webstorage.html

**Comment by ruanyf** [comment]
我正在修订这本书，这一章要重写，后面统一修改。

sessionStorage 不会传递，只有 localStorage 可以。
