### ISSUE TITLE
想咨询一个问题

### ISSUE THREAD

**Issue by hongtianpei1990gmail** [ruanyf/jstutorial#306]
阮老师好，感谢写了JavaScript 标准参考教程（alpha）这么好的教程，想咨询下老师是否可以写个javascript 实战方面的教程？， 把js标准教程所学的知识运用到实战中。

**Comment by ruanyf** [comment]
我的时间太少了，现在的内容都来不及写，应该不会写实战，何况我实战经验也不丰富。
