### ISSUE TITLE
contentEditable is readable

### ISSUE THREAD

**Issue by banli17** [ruanyf/jstutorial#309]
url :[https://github.com/ruanyf/jstutorial/blob/gh-pages/dom/element.md](https://github.com/ruanyf/jstutorial/blob/gh-pages/dom/element.md)

> Element.isContentEditable属性返回一个布尔值，同样表示是否设置了contenteditable属性。
这两个属性都是只读属性。

contentEditable 是可写的。最新chrome测试。

**Comment by ruanyf** [comment]
我测了一下。

```javascript
document.body.isContentEditable
// false
document.body.isContentEditable = true;
document.body.isContentEditable 
// false
```

**Comment by banli17** [comment]
是这样

```
document.body.contentEditable = true;   // 这里是 contentEditable
document.body.isContentEditable 
// true
```

**Comment by ruanyf** [comment]
这肯定是这样的。只读指的是本身不可写。

**Comment by ruanyf** [comment]
又看了一下，原来你是说 HTMLElement.contentEditable 可写。

这里确实写错了，我改一下。
