### ISSUE TITLE
对 >> 和 >>> 运算符的解释有误

### ISSUE THREAD

**Issue by ghost** [ruanyf/jstutorial#31]
引用：https://github.com/ruanyf/jstutorial/blob/gh-pages/grammar/operator.md#%E5%B8%A6%E7%AC%A6%E5%8F%B7%E4%BD%8D%E7%9A%84%E5%8F%B3%E7%A7%BB%E8%BF%90%E7%AE%97%E7%AC%A6

> 5.8 带符号位的右移运算符（>>>）
> ...
> -4带符号位右移一位，得到2147483646。这主要是因为在JavaScipt内部，-4以10000000000000000000000000000100的32位形式保存，最前面的1表示负值。带符号位右移一位时，这个值变成01000000000000000000000000000010，等于十进制的2147483646。

-4 是以 `11111111111111111111111111111100` 表示的，用 `>>>` 右移时，最高位补 0 ，得到 `01111111111111111111111111111100` ，即 2147483646 。

> 5.7 右移运算符（>>）
> 右移运算符表示将一个数的二进制形式向后移动，头部补0。
> ...
> 右移运算符移动时不包括符号位，所以-4右移1位，得到的还是负值。

`>>` 会根据符号位分别在正数和负数最高位补 0 或 1 。

可以用下面这个函数测试，规范说明在：http://www.ecma-international.org/ecma-262/5.1/#sec-11.7.2

``` javascript
function pb(n) {
  var s = '';
  while (n) {
    s = (n & 0x1) + s;
    n >>>= 1;  // >>= 1 will never end for negative integers
  }
  return s;
}
```

**Comment by ruanyf** [comment]
谢谢指出，刚发现这一部分完全写错，已经改正过来了。

**Comment by ghost** [comment]
哈，我上面也给转换后的结果多写了一个 0 。
