### ISSUE TITLE
Element对象这篇文章中offsetHeight描述有误

### ISSUE THREAD

**Issue by yulilong** [ruanyf/jstutorial#323]
https://javascript.ruanyifeng.com/dom/element.html#toc13

你在Element.offsetHeight描述中：
Element.offsetHeight属性返回一个整数，表示元素的 CSS 垂直高度（单位像素），包括元素本身的高度、padding 和 border，以及垂直滚动条的高度（如果存在滚动条）。

经过在mdn中查找：
元素的offsetHeight是一种元素CSS高度的衡量标准，包括元素的边框、内边距和元素的水平滚动条（如果存在且渲染的话），不包含:before或:after等伪类元素的高度。
https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement/offsetHeight

而你的描述是垂直滚动条， 应该改成 水平滚动条。

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
