### ISSUE TITLE
Element.getClientRects() 关于行内描述问题

### ISSUE THREAD

**Issue by yulilong** [ruanyf/jstutorial#324]
https://javascript.ruanyifeng.com/dom/element.html#toc30
你好，您关于Element.getClientRects() 方法介绍中有一段描述：

一个行内元素<span>，如果它在页面上占据三行，getClientRects方法返回的对象就有三个成员，如果它在页面上占据一行，getClientRects方法返回的对象就只有一个成员。

但是经过我的代码测试：

```html
<style>
    .one {
      width: 800px; border: 1px solid;
      font-size: 15px;
    }
  </style>
  <div class="one">
    <span id="inline">
      Hello World
      Hello World
      Hello World
    </span>
  </div>
  <script>
    var el = document.getElementById('inline');
    console.log(el.getClientRects().length);     // 3
    console.log(el.getClientRects());
  </script>
```
当给div设置宽度100px的时候，span元素占三行，el.getClientRects().length等于3，也就是您说的占据三行返回三个成员，
当给div设置宽度800px的时候，span元素占一行，el.getClientRects().length等于3，也是三个成员。

请问是我理解错了，还是您写错了？

如果你说的行内元素行数是指代码中的行数，那么下面的代码：

```
<style>
    .one {
      width: 800px; border: 1px solid;
      font-size: 15px;
    }
  </style>
  <div class="one">
    <span id="inline">
      Hello World
      Element.getClientRects方法返回一个类似数组的对象Element.getClientRects方法返回一个类似数组的对象Ele
    </span>
  </div>
  <script>
    var el = document.getElementById('inline');
    console.log(el.getClientRects().length); // 3
    console.log(el.getClientRects());
  </script>
```
代码中 span行内元素2行， 实际页面中也是2行， 但是el.getClientRects().length的值是3，请问这是什么情况

我代码测试的浏览器是Google 的 Chrome(版本 66.0.3359.181（正式版本） （64 位）)

**Comment by ruanyf** [comment]
我试了一下，如果写成一行 `<span>Hello World Hello World Hello World</span>`，返回就是1。看了换行符对这个有影响，我改一下文档。
