### ISSUE TITLE
关于事件模型中Event.detail中代码示例问题

### ISSUE THREAD

**Issue by yulilong** [ruanyf/jstutorial#325]
https://javascript.ruanyifeng.com/dom/event.html#toc20

阮老师你好，关于您在Event.detail中的代码描述：

```javascript
// HTML 代码如下
// <p>Hello</p>
function giveDetails(e) {
  console.log(e.detail);
}

document.selectQuery('p') = giveDetails;
```

请问这个selectQuery方法是什么？ 我在网络上没有搜索到方法的介绍。        
我在chrome浏览器测试这段代码报错：   
dayov:22 Uncaught TypeError: document.selectQuery is not a function     

请问这是什么情况？

**Comment by ruanyf** [comment]
不好意思是我写错了，已经改正。正确的写法如下。

```javascript
document.querySelector('p').onclick = giveDetails;
```
