### ISSUE TITLE
JavaScript标准参考教程中dom模型概述有一段话描述是不是有问题.

### ISSUE THREAD

**Issue by bosens-China** [ruanyf/jstutorial#329]
浏览器原生提供document节点，代表整个文档。
文档的第一层只有一个节点，就是 HTML 网页的第一个标签<html>，它构成了树结构的根节点（root node），其他 HTML 标签节点都是它的下级节点。

文档第一层不应该是文档类型么<!DOCTYPE html>

**Comment by bosens-China** [comment]
这个章节下的2.1有一段代码演示,不过这个应该是css样式出现了问题,文字变成黑色了
document.nodeType // 9

**Comment by bosens-China** [comment]
2.7Node.nextSibling
有一句说注意，该属性还包括文本节点和评论节点。因此如果当前节点后面有空格，该属性会返回一个文本节点，内容为空格。
老师如何理解评论节点

**Comment by ruanyf** [comment]
（1）文档的第一个节点是`<html>`。

（2）谢谢指出，已经更正。

（3） 评论节点就是注释节点`<!-- comment -->`，我改掉了。
