### ISSUE TITLE
commonJS规范 第 5节 模块的加载机制 描述有误

### ISSUE THREAD

**Issue by gm3000** [ruanyf/jstutorial#330]
‘’‘CommonJS模块的加载机制是，输入的是被输出的值的拷贝。也就是说，一旦输出一个值，模块内部的变化就影响不到这个值’‘’
实际上能影响，你的例子里用的变量值是个primary类型，这种类型是值传递，所以导出后就不能再看到变化了，如果用一个引用传递类型，比如object，那么还是能看到变化的

**Comment by ruanyf** [comment]
对象属性的变化是可以看到，因为对象是引用。
