### ISSUE TITLE
prototype 对象章节

### ISSUE THREAD

**Issue by yzajoee** [ruanyf/jstutorial#332]
当函数返回值为一个对象的时候，函数的constructor为返回的对象本身
![image](https://user-images.githubusercontent.com/13886165/53718971-b8a02e80-3e97-11e9-935e-5275ff31f429.png)

The second piece of magic eluded to above is the ability for a constructor to return a specific, possibly pre-existing object, rather than a reference to a new instance. This would allow you to manage the number of actual instances yourself if needed; possibly for reasons of limited resources or whatnot.

[引用地址](https://web.archive.org/web/20100216124827/http://www.gibdon.com/2008/08/javascript-constructor-return-value.html)

**Comment by ruanyf** [comment]
谢谢指出。
