### ISSUE TITLE
问一个同域策略相关的问题

### ISSUE THREAD

**Issue by dou4cc** [ruanyf/jstutorial#42]
现在有两个网站，一个是http://a.foo.cn/ ，一个是http://b.foo.cn/。
现在运行了http://a.foo.cn/ ，该网页代码中置document.domain为"foo.cn"，结果用XMLHttpRequest访问http://b.foo.cn/ 还是跳到CORS了，为什么？

**Comment by hanai** [comment]
b 也要设置 document.domain 为 foo.cn
