### ISSUE TITLE
index.md 超链接失效 及 在github中显示失效的语法

### ISSUE THREAD

**Issue by maosi** [ruanyf/jstutorial#43]
- 在`index.md`中,超链接是失效的,不能正确链接到对应的md路径
- 很多md文件中用到了 `{% highlight javascript %}`  和 `{% endhighlight %}` 语法,在github的md中是无法正确识别的
- 以上两个问题都是迁移问题

**Comment by JiayingZeng** [comment]
index.md 所有的链接后缀应该是 .md 才能链接到项目上的其它文件

**Comment by ruanyf** [comment]
These links are not for Github，but for the Web service.

**Comment by DrMundo0** [comment]
`{% highlight javascript %}` 和 `{% endhighlight %}` 是 Jekyll 中代码高亮包裹写法。不是错误。
