### ISSUE TITLE
标准库-Object对象-5.3 Object.seal方法 中最后一段话含义不清的讨论

### ISSUE THREAD

**Issue by Xiami2012** [ruanyf/jstutorial#45]
**stdlib/object.md** 中说到

> 但是，出于历史原因，这时依然可以将writable从true变成false，即可以对现有属性重新赋值。

给出的例子是：

> var o = { p: 'a' };
> 
> Object.seal(o);
> 
> o.p = 'b';
> o.p // 'b'

---

这里提到的将 writable 从 true 变成 false ，应该是指 _redefine property_ ，感觉翻译成 重新定义 比 重新赋值 更佳。

且原文附带的示例，是一段对 writable: true 的属性进行重新赋值的代码，属性的 value 是否可变和该对象是否封闭无关。有点混淆理解。

附上一个私以为更为合理的例子：

<pre>
var o = {p : ""}
Object.getOwnPropertyDescriptor(o, 'p')
/* { value: '',
  writable: true,
  enumerable: true,
  configurable: true } */

Object.seal(o)
Object.getOwnPropertyDescriptor(o, 'p')
/* { value: '',
  writable: true,
  enumerable: true,
  configurable: false } */

Object.defineProperty(o, 'p', {writable: false})
Object.getOwnPropertyDescriptor(o, 'p')
/* { value: '',
  writable: false,
  enumerable: true,
  configurable: false } */

// node v0.10.32
</pre>

**Comment by ruanyf** [comment]
谢谢指出，原来的例子确实不当，已经改过来了。

**Comment by Xiami2012** [comment]
现在的版本仍然有个描述上的小问题

> 但是，出于历史原因，这时依然可以将writable从true变成false，即seal方法对writable属性无效。

seal 之后是无法把 writable 从 false 变成 true 的，而 seal 之前可以。
仅仅是 seal 前后都可以将 writable 从 true 变为 false 。

_seal方法对writable属性无效_ 的措辞个人认为有点欠妥。这句话的理解应该是 seal 前后 **对 writable 属性的修改** 这个操作的结果不产生任何影响，但实际上如上文所述无法将 writable 从 false 变为 true 了。

测试环境：Firefox 33.0.2
测试代码：

<pre>
var o = {p : 0};
Object.getOwnPropertyDescriptor(o, 'p');
/* 未封闭 */
Object.defineProperty(o, 'p', {writable: false});
Object.getOwnPropertyDescriptor(o, 'p');
Object.defineProperty(o, 'p', {writable: true});
Object.getOwnPropertyDescriptor(o, 'p');
/* 封闭后 */
Object.seal(o);
Object.defineProperty(o, 'p', {writable: false});
Object.getOwnPropertyDescriptor(o, 'p');
Object.defineProperty(o, 'p', {writable: true});
Object.getOwnPropertyDescriptor(o, 'p');
</pre>

**Comment by ruanyf** [comment]
谢谢指出，改成下面这样了。

> 可写性（writable）有点特别。如果writable为false，使用Object.seal方法以后，将无法将其变成true；但是，如果writable为true，依然可以将其变成false。

``` javascript

var o1 = Object.defineProperty({}, 'p', {writable: false});
Object.seal(o1);
Object.defineProperty(o1,'p',{writable:true}) 
// Uncaught TypeError: Cannot redefine property: p 

var o2 = Object.defineProperty({}, 'p', {writable: true});
Object.seal(o2);
Object.defineProperty(o2,'p',{writable:false}) 

Object.getOwnPropertyDescriptor(o2, 'p')
/* { value: '',
  writable: false,
  enumerable: true,
  configurable: false } */

```

> 上面代码中，同样是使用了Object.seal方法，如果writable原为false，改变这个设置将报错；如果原为true，则不会有问题。
