### ISSUE TITLE
补充下圆括号的语法

### ISSUE THREAD

**Issue by jetiny** [ruanyf/jstutorial#49]
圆括号相当于一个匿名函数，并且把最后一个参数的结果返回。

var id=0;
var idplus = (++id, id++);
id === 2; //true
idplus === 1; //true

所以才有闭包的写法
(function(n){
})(1)
第一个()中的function当成函数返回，第二个()中的1则当作参数传入。

**Comment by ghost** [comment]
请问这个说法的出处在哪里？以下为括号算符的说明：

[http://www.ecma-international.org/ecma-262/5.1/#sec-11.1.6]()

返回最后一个值则是[逗号算符](http://www.ecma-international.org/ecma-262/5.1/#sec-11.14)的功能，与括号无关，除非它在参数列表中。

**Comment by ThomasHuke** [comment]
这个iss提的完全没有水准，这些问题纯粹是优先级的问题，并且我认为在编程中应该避免这种一眼看不出来编程意向的方式，使用规范的方式。使用 var a = ( a1++, b1++ ) ，看起来真的很丑陋。另外加上括号是为了让逗号运算符的起作用优先于 赋值运算符，所以才加上括号这个优先级最高的符号的。

**Comment by ruanyf** [comment]
圆括号没有匿名函数的作用。
