### ISSUE TITLE
clone了您的tutorial到本地了，怎么生成html本地浏览？

### ISSUE THREAD

**Issue by xu4wang** [ruanyf/jstutorial#50]
clone了您的tutorial到本地了，怎么生成html本地浏览？ 谢谢

**Comment by appleboy** [comment]
see [Creating Project Pages manually](https://help.github.com/articles/creating-project-pages-manually/)

**Comment by okuc** [comment]
mark，good。Think you！

**Comment by supgeek-rod** [comment]
听说gh-pages是使用`jekyll`生成静态HTML 
[http://jekyllcn.com](http://jekyllcn.com)
