### ISSUE TITLE
javascript测试

### ISSUE THREAD

**Issue by surpmillet** [ruanyf/jstutorial#53]
感谢@ruanyf无私的付出，你的教程对于我这样的新手很有指导意义。希望能增加测试驱动js开发的章节

**Comment by appleboy** [comment]
@ruanyf ++ 感謝付出

**Comment by Shyam-Chen** [comment]
測試並不包含在標準的 JS 中，要了解測試，還需要有設計模式的概念，而且還涉及了選擇測試框架的問題

**Comment by ruanyf** [comment]
JavaScript 测试可以单独写一本书，我没足够时间投入这个主题了，研究不深就不写了。
