### ISSUE TITLE
关于 `Promise对象` 这篇文章中的一些问题

### ISSUE THREAD

**Issue by xqin** [ruanyf/jstutorial#78]
文章连接:  http://javascript.ruanyifeng.com/advanced/promise.html

首先`Promise` 的构造函数如下:

```
var Promise = function () {
  this.state = 'pending';
  this.thenables = [];
};
```

然后您在后面给出的例子是下面这样的:

```
var preloadImage = function (path) {
  return new Promise(function (resolve, reject) {
    var image = new Image();
    image.onload  = resolve;
    image.onerror = reject;
    image.src = path;
  });
};
```

我不知道您在写(或者说翻译)这篇文章的时候是否有真的运行过你文章的代码(哪怕只运行一次),
您就应该能发现, 这个 `preloadImage` 在实现上是错误的.
因为 `Promise` 的构造函数并不接收任何参数,
所以这里传递过去的`function`不会被任何人调用,
如果没有地方调用这个方法,那么这个图片浏览器永远不会去加载,也就没有`preload`的效果了.

**Comment by ruanyf** [comment]
后面例子的Promise是ES6的写法，前面的实现不是，只为了说明Promise是什么。

我找时间改一下。
