### ISSUE TITLE
有关isNaN部分的一点小问题

### ISSUE THREAD

**Issue by tommytroylin** [ruanyf/jstutorial#81]
出于同样的原因，对于数组和对象，isNaN也返回true。

```
isNaN({}) // true
isNaN(Number({})) // true

isNaN(["xzy"]) // true
```

   isNaN(Number(["xzy"])) // true

事实上 用Number转型的时候

```
Number([])
// 0
Number(["123"])
// 123
Number(["123","213"])
// NaN
```

有一些特殊数组是可以被转化为`number` 类型的，isNaN的结果也为false
因此 `对于数组和对象` 这句话有点不太确切。希望能做出修改

谢谢您的教程

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
