### ISSUE TITLE
单词拼写错误

### ISSUE THREAD

**Issue by dwqs** [ruanyf/jstutorial#82]
http://javascript.ruanyifeng.com/dom/element.html

> （1）getClientRects()
> getClientRects方法返回一个类似数组的对象，里面是当前元素在页面上形成的所有矩形。每个矩形都有botto、height、left、right、top和width六个属性，表示它们相对于视口的四个坐标，以及本身的高度和宽度。

botto 应该改为bottom

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
