### ISSUE TITLE
数据陈述有误

### ISSUE THREAD

**Issue by dwqs** [ruanyf/jstutorial#83]
> vibrate方法还可以接受一个数组作为参数，表示振动的模式。偶数位置的数组成员表示振动的毫秒数，奇数位置的数组成员表示等待的毫秒数。
> navigator.vibrate([500, 300, 100]);
> 上面代码表示，设备先振动500毫秒，然后等待300毫秒，再接着振动500毫秒。

http://javascript.ruanyifeng.com/bom/mobile.html#

**Comment by ruanyf** [comment]
谢谢指出，已改正。
