### ISSUE TITLE
javascript关于setInterval函数的疑惑

### ISSUE THREAD

**Issue by keshidong** [ruanyf/jstutorial#94]
``` javascript
var i = 1;
var timer = setInterval(function() {
  alert(i++);
}, 2000);
```

我在谷歌浏览器控制台测试了下这段代码，并没有像 [文中](http://javascript.ruanyifeng.com/bom/timer.html)所说的那样。1. 后面的执行没有立即触发，仍然有2s的等待间隔。2. 第二次，第三次，第四次执行并不会累加起来。

> 上面代码每隔2000毫秒，就跳出一个alert对话框。如果用户一直不点击“确定”，整个浏览器就处于“堵塞”状态，后面的执行就一直无法触发，将会累积起来。举例来说，第一次跳出alert对话框后，用户过了6000毫秒才点击“确定”，那么第二次、第三次、第四次执行将累积起来，它们之间不会再有等待间隔.

**Comment by TingGe** [comment]
@keshidong 我刚才也在谷歌浏览器控制台测试了下，你说的情况，应该是多次执行这段代码的情况，如果只执行一次和文中说的是一样的。

**Comment by hkongm** [comment]
例子可能不恰当，这种情况需要 **挤** 出来。
通常下，当你的定时器里的代码，执行时间要大于你的第二个参数所设定的时间时，必然出现。
试着在一秒内，更新1000个DOM操作，再顺序执行这么几个定时器吧。

**Comment by ystarlongzi** [comment]
> 如果用户一直不点击“确定”，整个浏览器就处于“堵塞”状态，后面的执行就一直无法触发，将会累积起来

实际上如果你不点击『确定』按钮，后面的定时都会被 dropped 掉，而不是累加。所以这里描述的并不准确。还有这里关于 [timer 运行机制](https://github.com/ruanyf/jstutorial/blob/gh-pages/advanced/timer.md#运行机制) 的描述

> 结果就是等到第二行语句运行完成以后，立刻连续输出三个2，然后开始每隔1000毫秒，输出一个2。也就是说，setIntervel具有累积效应，如果某个操作特别耗时，超过了setInterval的时间间隔，排在后面的操作会被累积起来，然后在很短的时间内连续触发

希望 @ruanyf 老师能修改下。

https://johnresig.com/blog/how-javascript-timers-work/
![image](https://cloud.githubusercontent.com/assets/2840462/25889868/eea69f28-359d-11e7-8c71-ba0db23d9167.png)

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
