### ISSUE TITLE
array中的arguments变成真正的数组

### ISSUE THREAD

**Issue by de8ug** [ruanyf/jstutorial#99]
文件：
[https://github.com/ruanyf/jstutorial/blob/gh-pages/grammar/array.md](https://github.com/ruanyf/jstutorial/blob/gh-pages/grammar/array.md)

```
通过函数的call方法，可以用slice方法将类似数组的对象，变成真正的数组。
var arr = Array.prototype.slice.call(arguments);
```

这里的参数`arguments`一开始没太明白，是否改成连接上文例子中的 `arrayLike`更容易理解呢？

**Comment by ruanyf** [comment]
谢谢指出，改过来了
